# Generated by Django 3.2.3 on 2021-05-24 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airApp', '0005_auto_20210522_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='airApp.user'),
        ),
        migrations.RemoveField(
            model_name='house',
            name='roomtype',
        ),
        migrations.AddField(
            model_name='house',
            name='roomtype',
            field=models.ManyToManyField(blank=True, default='', null=True, to='airApp.HouseType'),
        ),
    ]
